#!/bin/bash

echo "You are trying to replace"
echo "From: ${1}"
echo "To: ${2}"
read -p "Are you sure? <y/n>" prompt
if [ ${prompt} != y ]; then
    echo "Please retry"
    exit 0
fi

if [ ${1} == "-recover" ]; then
  echo "recovery mode"
  if [ -e {*.replace.bak} ]; then
    echo No file exists to replace.
    exit 0
  fi
  echo "Not Implemented Yet."
  for file in $(find . -name "*.replace.bak")
  do 
        testtruefile=${testfile%.*.*}
        echo "testtruefile becomes $testtruefile"
        truefilename=${file%.*.*}
        cp $file $truefilename
        rm $file
        echo "${file} has been recovered!"
  done
  exit 0
fi

echo Converting $1 to $2... 
for file in $(grep -lr "$1" *)
do
    sed -i.replace.bak s/$1/$2/g $file
    echo $file is converted.
done
