# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

if [ -f "$HOME/env/files/tmux.conf" ]; then
    tmux source-file "$HOME/env/files/tmux.conf"
fi

alias ocrt="ssh cdevgpu-ocr001.papago"
export PATH="$HOME/.poetry/bin:$PATH"
